parser:
  _target_: py123d.parser.kitti360.kitti360_parser.Kitti360Parser
  _convert_: 'all'

  splits: ["kitti360_train", "kitti360_val", "kitti360_test"]

  kitti360_data_root: ${dataset_paths.kitti360_data_root}

  # NOTE: We preprocess detections into cache directory to speed up repeated conversions
  # The bounding boxes are preprocessed into a per-frame format based on the ego distance and
  # visibility based on the lidar point cloud.
  detection_cache_root: ${dataset_paths.kitti360_data_root}/preprocessed_detections
  detection_radius: 60.0

  # NOTE: KITTI-360 does not have official splits, so we just put all sequences in the training set.
  train_sequences:
    - "2013_05_28_drive_0000_sync"
    - "2013_05_28_drive_0002_sync"
    - "2013_05_28_drive_0003_sync"
    - "2013_05_28_drive_0004_sync"
    - "2013_05_28_drive_0005_sync"
    - "2013_05_28_drive_0006_sync"
    - "2013_05_28_drive_0007_sync"
    - "2013_05_28_drive_0009_sync"
    - "2013_05_28_drive_0010_sync"

  val_sequences: []
  test_sequences: []

log_writer_config:
  _target_: py123d.api.scene.arrow.utils.log_writer_config.LogWriterConfig
  _convert_: 'all'

  force_log_conversion: ${force_log_conversion}
  force_map_conversion: ${force_map_conversion}
  async_conversion: ${async_conversion}

  camera_store_option: "path" # "path", "jpeg_binary", "png_binary"
  lidar_store_option: "path" #  "path", "binary"
  lidar_codec: null # None or "laz", "draco", "ipc_zstd", "ipc_lz4", "ipc"

  infer_ego_dynamics: true
  infer_box_dynamics: true

log_writer:
  _target_: py123d.api.scene.arrow.arrow_log_writer.ArrowLogWriter
  _convert_: 'all'
  log_writer_config: ${dataset.log_writer_config}
  logs_root: ${dataset_paths.py123d_logs_root}
  sensors_root: ${dataset_paths.py123d_sensors_root}
  ipc_compression: null
  ipc_compression_level: null

  sync_config:
    _target_: py123d.api.scene.arrow.arrow_log_writer.SyncConfig
    _convert_: 'all'
    reference_column: lidar.lidar_top.timestamp_us
    direction: "forward" # "forward" or "backward"

map_writer:
  _target_: py123d.api.map.arrow.arrow_map_writer.ArrowMapWriter
  _convert_: 'all'
  force_map_conversion: ${force_map_conversion}
  maps_root: ${dataset_paths.py123d_maps_root}
  logs_root: ${dataset_paths.py123d_logs_root}
