parser:
  _target_: py123d.parser.nuscenes.nuscenes_parser.NuScenesParser
  _convert_: 'all'

  splits: ["nuscenes-interpolated_train", "nuscenes-interpolated_val", "nuscenes-interpolated_test"]
  nuscenes_data_root: ${dataset_paths.nuscenes_data_root}
  nuscenes_map_root: ${dataset_paths.nuscenes_map_root}

log_writer_config:
  _target_: py123d.api.scene.arrow.utils.log_writer_config.LogWriterConfig
  _convert_: 'all'

  force_log_conversion: ${force_log_conversion}
  force_map_conversion: ${force_map_conversion}

  camera_store_option: "path" # "path", "jpeg_binary", "png_binary"

  lidar_store_option: "path" #  "path", "binary"
  lidar_codec: null # None or "laz", "draco", "ipc_zstd", "ipc_lz4", "ipc"

log_writer:
  _target_: py123d.api.scene.arrow.arrow_log_writer.ArrowLogWriter
  _convert_: 'all'
  log_writer_config: ${dataset.log_writer_config}
  logs_root: ${dataset_paths.py123d_logs_root}
  sensors_root: ${dataset_paths.py123d_sensors_root}
  ipc_compression: null
  ipc_compression_level: null

  sync_config:
    _target_: py123d.api.scene.arrow.arrow_log_writer.SyncConfig
    _convert_: 'all'
    reference_column: box_detections_se3.timestamp_us
    direction: "backward" # "forward" or "backward"

map_writer:
  _target_: py123d.api.map.arrow.arrow_map_writer.ArrowMapWriter
  _convert_: 'all'
  force_map_conversion: ${force_map_conversion}
  maps_root: ${dataset_paths.py123d_maps_root}
  logs_root: ${dataset_paths.py123d_logs_root}
