parser:
  _target_: py123d.parser.physical_ai_av.physical_ai_av_parser.PhysicalAIAVParser
  _convert_: 'all'

  splits: ["physical-ai-av_train"]
  physical_ai_av_data_root: ${dataset_paths.physical_ai_av_data_root}
  max_clips: null

log_writer_config:
  _target_: py123d.api.scene.arrow.utils.log_writer_config.LogWriterConfig
  _convert_: 'all'

  force_log_conversion: ${force_log_conversion}
  force_map_conversion: ${force_map_conversion}
  async_conversion: ${async_conversion}

  camera_store_option: "jpeg_binary" # "path", "jpeg_binary", "png_binary", "mp4"
  lidar_store_option: "binary" #  "path", "binary"
  lidar_codec: "ipc_lz4" # None or "laz", "draco", "ipc_zstd", "ipc_lz4", "ipc"

  infer_ego_dynamics: true
  infer_box_dynamics: true

log_writer:
  _target_: py123d.api.scene.arrow.arrow_log_writer.ArrowLogWriter
  _convert_: 'all'
  log_writer_config: ${dataset.log_writer_config}
  logs_root: ${dataset_paths.py123d_logs_root}
  sensors_root: ${dataset_paths.py123d_sensors_root}
  ipc_compression: null
  ipc_compression_level: null

  sync_config:
    _target_: py123d.api.scene.arrow.arrow_log_writer.SyncConfig
    _convert_: 'all'
    reference_column: lidar.lidar_merged.timestamp_us
    direction: "forward" # "forward" or "backward"

map_writer:
  _target_: py123d.api.map.arrow.arrow_map_writer.ArrowMapWriter
  _convert_: 'all'
  force_map_conversion: ${force_map_conversion}
  maps_root: ${dataset_paths.py123d_maps_root}
  logs_root: ${dataset_paths.py123d_logs_root}
