hydra:
  output_subdir: null
  run:
    dir: .
  searchpath:
    - pkg://py123d.script.config
    - pkg://py123d.script.config.common
  job:
    chdir: False

defaults:
  - default_common
  - default_dataset_paths
  - dataset: av2-sensor
  - _self_


logger_level: info  # "debug", "info", "warning", "error"

terminate_on_exception: True

force_map_conversion: True
force_log_conversion: True
async_conversion: False
