hydra:
  output_subdir: null
  run:
    dir: .
  searchpath:
    - pkg://py123d.script.config
    - pkg://py123d.script.config.common
  job:
    chdir: False
#
defaults:
  - default_common
  - default_dataset_paths
  - override scene_filter: viser_scenes
  - override execution: thread_pool_executor
  - _self_

logger_level: info  # "debug", "info", "warning", "error"

viser_config:
  _target_: py123d.visualization.viser.viser_config.ViserConfig
  _convert_: 'all'

  server:
    host: "localhost"
    port: 8080
    label: "123D Viser Server"
    verbose: true

  theme:
    control_layout: "collapsible" # ["floating", "collapsible", "fixed"]
    control_width: "large" # ["small", "medium", "large"]
    dark_mode: true
    show_logo: true
    show_share_button: true

  playback:
    is_playing: false
    speed: 1.0
    atomic: false
