from py123d.datatypes.custom import CustomModality, CustomModalityMetadata
from py123d.datatypes.detections import (
    BOX_DETECTION_LABEL_REGISTRY,
    BoxDetection,
    BoxDetectionAttributes,
    BoxDetectionLabel,
    BoxDetectionSE2,
    BoxDetectionSE3,
    BoxDetectionsSE2,
    BoxDetectionsSE3,
    BoxDetectionsSE3Metadata,
    DefaultBoxDetectionLabel,
    TrafficLightDetection,
    TrafficLightDetections,
    TrafficLightDetectionsMetadata,
    TrafficLightStatus,
    register_box_detection_label,
)
from py123d.datatypes.map_objects import (
    BaseMapLineObject,
    BaseMapObject,
    BaseMapSurfaceObject,
    Carpark,
    Crosswalk,
    GenericDrivable,
    Intersection,
    IntersectionType,
    Lane,
    LaneGroup,
    LaneType,
    MapLayer,
    RoadEdge,
    RoadEdgeType,
    RoadLine,
    RoadLineType,
    StopZone,
    StopZoneType,
    Walkway,
)
from py123d.datatypes.metadata import BaseMetadata, MapMetadata, SceneMetadata

# LogMetadata imported after all deps to avoid circular import
# (log_metadata -> custom_modality -> metadata.base_metadata -> metadata/__init__ cycle)
from py123d.datatypes.metadata.log_metadata import LogMetadata
from py123d.datatypes.modalities import (
    BaseModality,
    BaseModalityMetadata,
    ModalityType,
    get_modality_id_from_key,
    get_modality_key,
)
from py123d.datatypes.sensors import (
    BaseCameraMetadata,
    Camera,
    CameraChannelType,
    CameraID,
    CameraMetadata,
    CameraModel,
    FisheyeMEICameraMetadata,
    FisheyeMEIDistortion,
    FisheyeMEIDistortionIndex,
    FisheyeMEIProjection,
    FisheyeMEIProjectionIndex,
    FThetaCameraMetadata,
    FThetaIntrinsics,
    FThetaIntrinsicsIndex,
    Lidar,
    LidarFeature,
    LidarID,
    LidarMergedMetadata,
    LidarMetadata,
    PinholeCameraMetadata,
    PinholeDistortion,
    PinholeDistortionIndex,
    PinholeIntrinsics,
    PinholeIntrinsicsIndex,
    camera_metadata_from_dict,
)
from py123d.datatypes.time import Timestamp
from py123d.datatypes.vehicle_state import (
    DynamicStateSE2,
    DynamicStateSE2Index,
    DynamicStateSE3,
    DynamicStateSE3Index,
    EgoStateSE2,
    EgoStateSE3,
    EgoStateSE3Metadata,
)

__all__ = [
    # Custom
    "CustomModality",
    "CustomModalityMetadata",
    # Detections
    "BOX_DETECTION_LABEL_REGISTRY",
    "BoxDetection",
    "BoxDetectionAttributes",
    "BoxDetectionLabel",
    "BoxDetectionSE2",
    "BoxDetectionSE3",
    "BoxDetectionsSE2",
    "BoxDetectionsSE3",
    "BoxDetectionsSE3Metadata",
    "DefaultBoxDetectionLabel",
    "TrafficLightDetection",
    "TrafficLightDetections",
    "TrafficLightDetectionsMetadata",
    "TrafficLightStatus",
    "register_box_detection_label",
    # Map objects
    "BaseMapLineObject",
    "BaseMapObject",
    "BaseMapSurfaceObject",
    "Carpark",
    "Crosswalk",
    "GenericDrivable",
    "Intersection",
    "IntersectionType",
    "Lane",
    "LaneGroup",
    "LaneType",
    "MapLayer",
    "RoadEdge",
    "RoadEdgeType",
    "RoadLine",
    "RoadLineType",
    "StopZone",
    "StopZoneType",
    "Walkway",
    # Metadata
    "BaseMetadata",
    "LogMetadata",
    "MapMetadata",
    "SceneMetadata",
    # Modalities
    "BaseModality",
    "BaseModalityMetadata",
    "ModalityType",
    "get_modality_id_from_key",
    "get_modality_key",
    # Sensors
    "BaseCameraMetadata",
    "Camera",
    "CameraChannelType",
    "CameraID",
    "CameraMetadata",
    "CameraModel",
    "FThetaCameraMetadata",
    "FThetaIntrinsics",
    "FThetaIntrinsicsIndex",
    "FisheyeMEICameraMetadata",
    "FisheyeMEIDistortion",
    "FisheyeMEIDistortionIndex",
    "FisheyeMEIProjection",
    "FisheyeMEIProjectionIndex",
    "Lidar",
    "LidarFeature",
    "LidarID",
    "LidarMergedMetadata",
    "LidarMetadata",
    "PinholeCameraMetadata",
    "PinholeDistortion",
    "PinholeDistortionIndex",
    "PinholeIntrinsics",
    "PinholeIntrinsicsIndex",
    "camera_metadata_from_dict",
    # Time
    "Timestamp",
    # Vehicle state
    "DynamicStateSE2",
    "DynamicStateSE2Index",
    "DynamicStateSE3",
    "DynamicStateSE3Index",
    "EgoStateSE2",
    "EgoStateSE3",
    "EgoStateSE3Metadata",
]
